#ifndef MAKROS_H
#define MAKROS_H


#define LED_BIT_COUNT 24
#define SLA_LENGTH_MAX 300
#define GRAPHICS_DATA_SIZE SLA_LENGTH_MAX*LED_BIT_COUNT
#define SLA_NUMBER 8
#define MODE_PARAMETER_NUMBER 10
#define MODE_ACTOR_NUMBER 10

#define GRAPHICS_GAMMA8_MAX_IN 255
#define GRAPHICS_GAMMA8_MAX_OUT 255
#define SETTINGS_GAMMA8_RED_DEFAULT 2.8
#define SETTINGS_GAMMA8_GREEN_DEFAULT 2.8
#define SETTINGS_GAMMA8_BLUE_DEFAULT 2.8

#define SLA_ACTIVE 1
#define SLA_DEACTIVE 0

#define TRUE 1
#define FALSE 0

#endif /* MAKROS_H */
